export const hotels = [
  {
    name: 'Tokyo Luxury Hotel',
    rating: 4.5,
    price: 200,
    currency: 'USD',
    provider: 'Bookings.com',
    images: [
      'https://plus.unsplash.com/premium_photo-1661962739798-0af59dc30d14?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aG90ZWwlMjByb29tJTIwd2l0aCUyMGJlZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
    ],
    amenities: {
      gym: true,
      pool: true,
      spa: true,
      restaurant: true,
      wifi: true,
    },
    pros: 'This hotel is closest to all the attractions you want to see. It is also the most luxurious hotel in Tokyo. You will have a great time here. It has a gym, pool, spa, free, wifi and restaurant. Breakfast and dinner are included in the price.',
    cons: 'This hotel is the most expensive hotel in Tokyo. It is also the furthest from the airport. It will use up most of your budget.',
    nearbyAttractions: ['Tokyo Tower', 'Imperial Palace', 'Shinjuku Gyoen National Garden'],
    address: '123 Tokyo Street, Minato, Tokyo, Japan',
  },
  {
    name: 'Tokyo Boutique Hotel',
    rating: 4.0,
    price: 150,
    currency: 'USD',
    provider: 'Hotels.com',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
      'https://example.com/tokyo-boutique-hotel-2.jpg',
    ],
    amenities: {
      gym: false,
      pool: false,
      spa: false,
      restaurant: true,
      wifi: true,
    },
    pros: 'This hotel is closest to the airport. It is well within your budget. The night life is booming around this here and it is located in the cleanest region in the world. It has a gym, free, wifi and restaurant. Breakfast is included in the price.',
    cons: 'It is also the furthest from the metro. You will use up most of your budget on transportation to your actvities.',
    nearbyAttractions: ['Ueno Park', 'Asakusa Shrine', 'Akihabara'],
    address: '456 Tokyo Street, Taito, Tokyo, Japan',
  },
  {
    name: 'Tokyo Budget Inn',
    rating: 3.0,
    price: 50,
    currency: 'USD',
    provider: 'Bookings.com',
    images: [
      'https://images.unsplash.com/photo-1642821236396-ddf27146a316?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8amFwYW4lMjBob3RlbCUyMGxvYmJ5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      'https://example.com/tokyo-budget-inn-2.jpg',
    ],
    amenities: {
      gym: false,
      pool: false,
      spa: false,
      restaurant: false,
      wifi: true,
    },
    pros: 'This hotel is closest to the metro. It is also the most budget friendly hotel located within a short enough distance to your activities. It has free, wifi.',
    cons: 'No meals are included in the price.',
    nearbyAttractions: ['Tsukiji Fish Market', 'Odaiba', 'Meiji Shrine'],
    address: '789 Tokyo Street, Shibuya, Tokyo, Japan',
  },
];
